# Generated by Django 4.2.4 on 2023-10-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='regtype',
            field=models.CharField(default='Student', max_length=30),
        ),
    ]
